version: '3'

tasks:
  run:
    desc: Run development server with auto-reload
    cmds:
      - find . -name '*.go' | entr -r go run ./cmd/server

  build:
    desc: Build server binary
    cmds:
      - go build -o bin/server ./cmd/server

  build:stats:
    desc: Build stats analyzer binary
    cmds:
      - go build -o bin/stats ./cmd/stats

  test:
    desc: Test all packages
    cmds:
      - gotestsum --format testname

  test:integration:
    desc: Run all integration tests (requires FFmpeg)
    cmds:
      - gotestsum --format testname -- -tags=integration -v ./...

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod tidy
